### ISSUE TITLE
Issue with read_psid()

### ISSUE THREAD

**Issue by haanbik19** [Qcrates/psidread#2]
Hi, I am trying to use the package to merge FAM variables to the individual study. I have used the unzip function to prepare the data sets in `.rda` format and am trying to merge the datasets using `read_psid()`. I am having a problem with initializing this as I am putting the correct directory for `indir` in the console (the one where I stored the new `.rda` files). But, I am getting the following error: `Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open file '/Desktop/Data/collected_data_1997-2021/': it is a directory`. I'm very confused by this and would need some assistance.

Edit: After playing around, I don't think it is an issue with the directory as I have used the variable codes in the examples and it worked just fine - when I use the variables I assigned I'm getting the issue.

<img width="1396" alt="image" src="https://github.com/user-attachments/assets/20cd822c-08bf-4623-b4dd-459d6093bbeb">

**Comment by Qcrates** [comment]
Hi! Thanks for reaching out! I received a feedback from another channel reporting the same issue, and it has been solved by downloading the wealth dataset in that wave. Please note that for some years (e.g. 2001, 2003...), wealth dataset is separately packaged. If you have variables to be extracted from wealth dataset, please make sure that you have the .zip file in the working directory.
